"""NPG Lite ECG loading and transparent R--R gating support.

The ECG supplies time, not subject-specific anatomy.  Raw samples are retained
unchanged; a zero-phase review copy is used only for display and R-peak
detection.  Mechanical phases remain estimates generated by :mod:`timing`.
"""

from __future__ import annotations

import csv
import hashlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

import numpy as np
from scipy.signal import butter, filtfilt, find_peaks, iirnotch

from .ecg_landmarks import (
    ECGMedianTemplate,
    ECGLandmark,
    ELECTRICAL_KINDS,
    LANDMARK_SPECS,
    LEGACY_T_KINDS,
    TEMPLATE_EDITABLE_KINDS,
    annotation_payload,
    build_median_template,
    load_annotation_sidecar,
    project_template_landmarks,
    save_annotation_sidecar,
    suggest_landmarks,
)


DEFAULT_ECG_FS_HZ = 500.0
ECG_REVIEW_BAND_HZ = (0.5, 40.0)
ECG_NOTCH_HZ = 50.0


def _normalise_header(value: str) -> str:
    return str(value).strip().lower().replace(" ", "_").replace("-", "_")


def _read_numeric_csv(path: Path) -> tuple[list[str], dict[str, np.ndarray]]:
    with Path(path).open("r", newline="", encoding="utf-8-sig", errors="replace") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            raise ValueError("The ECG CSV has no header row.")
        headers = [str(name) for name in reader.fieldnames]
        values: dict[str, list[float]] = {name: [] for name in headers}
        for row in reader:
            for name in headers:
                raw = row.get(name, "")
                try:
                    values[name].append(float(raw) if raw not in (None, "") else np.nan)
                except (TypeError, ValueError):
                    values[name].append(np.nan)
    if not values or not len(next(iter(values.values()))):
        raise ValueError("The ECG CSV contains no data rows.")
    return headers, {name: np.asarray(column, dtype=float) for name, column in values.items()}


def _choose_time_column(headers: Iterable[str]) -> tuple[str | None, float]:
    normalised = {_normalise_header(name): name for name in headers}
    for candidate, scale in (
        ("sample_time_s", 1.0),
        ("time_s", 1.0),
        ("seconds", 1.0),
        ("time", 1.0),
        ("pc_time_s", 1.0),
        ("time_us", 1e-6),
        ("timestamp_us", 1e-6),
        ("time_ms", 1e-3),
        ("timestamp_ms", 1e-3),
    ):
        if candidate in normalised:
            return normalised[candidate], scale
    return None, 1.0


def _is_signal_column(name: str, values: np.ndarray) -> bool:
    compact = _normalise_header(name)
    blocked = (
        "time",
        "sample",
        "segment",
        "index",
        "counter",
        "packet",
        "marker",
        "event",
    )
    if any(token in compact for token in blocked):
        return False
    finite = values[np.isfinite(values)]
    return len(finite) >= max(100, int(0.8 * len(values))) and np.ptp(finite) > 0


def _choose_signal_column(headers: Iterable[str], columns: dict[str, np.ndarray]) -> str:
    candidates = [name for name in headers if _is_signal_column(name, columns[name])]
    if not candidates:
        raise ValueError("No populated ECG-like channel was found in the CSV.")
    normalised = {name: _normalise_header(name).replace("_", "") for name in candidates}
    for token in ("ch1", "channel1", "ecg", "lead", "a0"):
        for name in candidates:
            if token in normalised[name]:
                return name
    return max(
        candidates,
        key=lambda name: float(
            np.nanpercentile(columns[name], 99) - np.nanpercentile(columns[name], 1)
        ),
    )


def _sampling_rate(time_s: np.ndarray) -> float:
    delta = np.diff(np.asarray(time_s, dtype=float))
    positive = delta[np.isfinite(delta) & (delta > 0)]
    if not len(positive):
        raise ValueError("The ECG time column is not increasing.")
    fs = float(1.0 / np.median(positive))
    if not 50.0 <= fs <= 4000.0:
        raise ValueError(f"Implausible ECG sampling rate: {fs:.1f} Hz.")
    return fs


def filter_ecg_for_review(raw_signal: np.ndarray, fs_hz: float) -> np.ndarray:
    """Return a review/detection copy without modifying ``raw_signal``."""

    raw = np.asarray(raw_signal, dtype=float)
    if len(raw) < max(30, int(fs_hz)):
        raise ValueError("ECG recording is too short for safe zero-phase filtering.")
    prepared = raw.copy()
    finite = np.isfinite(prepared)
    if not finite.all():
        prepared[~finite] = np.nanmedian(prepared[finite]) if finite.any() else 0.0
    low, high = ECG_REVIEW_BAND_HZ
    b, a = butter(4, [low, min(high, 0.90 * fs_hz / 2.0)], btype="bandpass", fs=fs_hz)
    filtered = filtfilt(b, a, prepared)
    if ECG_NOTCH_HZ < fs_hz / 2.0:
        notch_b, notch_a = iirnotch(ECG_NOTCH_HZ, 30.0, fs=fs_hz)
        filtered = filtfilt(notch_b, notch_a, filtered)
    return np.asarray(filtered, dtype=float)


def detect_r_peaks(raw_signal: np.ndarray, filtered_signal: np.ndarray, fs_hz: float) -> np.ndarray:
    """Detect reviewable R triggers with the OpenPhysiologyLab strategy.

    The already zero-phase-filtered trace is made polarity agnostic, then a
    robust MAD height/prominence rule and a 450 ms refractory interval are
    applied.  This is a timing trigger detector, not rhythm classification.
    """

    del raw_signal  # retained in the public signature for patch compatibility
    review = np.asarray(filtered_signal, dtype=float)
    if len(review) < 20:
        return np.array([], dtype=int)
    centred = review - float(np.nanmedian(review))
    inverted = -centred
    working = (
        inverted
        if np.nanpercentile(inverted, 99) > np.nanpercentile(centred, 99)
        else centred
    )
    robust = float(np.nanmedian(np.abs(working - np.nanmedian(working))) * 1.4826)
    if not np.isfinite(robust) or robust <= 0:
        robust = float(np.nanstd(working))
    if not np.isfinite(robust) or robust <= 0:
        return np.array([], dtype=int)
    baseline = float(np.nanmedian(working))
    prominence = max(
        1.5 * robust,
        0.35 * (float(np.nanpercentile(working, 98)) - baseline),
    )
    peaks, _ = find_peaks(
        working,
        distance=max(1, int(round(0.45 * fs_hz))),
        height=baseline + robust,
        prominence=max(prominence, np.finfo(float).eps),
    )
    return np.asarray(peaks, dtype=int)


@dataclass
class ECGGatingRecording:
    """One loaded ECG with reviewable electrical and mechanical annotations."""

    source_path: Path
    source_sha256: str
    time_s: np.ndarray
    raw_signal: np.ndarray
    filtered_signal: np.ndarray
    fs_hz: float
    channel_name: str
    time_column_name: str
    r_peaks: np.ndarray
    quality_flags: list[str] = field(default_factory=list)
    landmarks: list[ECGLandmark] = field(default_factory=list)
    median_template: ECGMedianTemplate | None = field(default=None, repr=False)

    def __post_init__(self) -> None:
        self.r_peaks = np.asarray(self.r_peaks, dtype=int)
        if self.median_template is None and len(self.r_peaks):
            self._rebuild_median_template(preserve_reviewed=False)
        if not self.landmarks and len(self.r_peaks):
            self.landmarks = suggest_landmarks(
                self.filtered_signal, self.r_peaks, self.fs_hz, self.median_template
            )

    @classmethod
    def from_csv(cls, path: Path) -> "ECGGatingRecording":
        path = Path(path)
        headers, columns = _read_numeric_csv(path)
        time_name, time_scale = _choose_time_column(headers)
        channel_name = _choose_signal_column(headers, columns)
        raw = np.asarray(columns[channel_name], dtype=float)
        if time_name is None:
            time = np.arange(len(raw), dtype=float) / DEFAULT_ECG_FS_HZ
            time_name = "generated_500_hz_time"
        else:
            time = np.asarray(columns[time_name], dtype=float) * float(time_scale)
            time = time - float(time[0])
        finite = np.isfinite(time) & np.isfinite(raw)
        if int(np.sum(finite)) < max(1000, int(0.8 * len(raw))):
            raise ValueError("Too many missing values in the ECG time or signal column.")
        time = time[finite]
        raw = raw[finite]
        if np.any(np.diff(time) <= 0):
            raise ValueError("ECG sample times must be strictly increasing.")
        fs = _sampling_rate(time)
        filtered = filter_ecg_for_review(raw, fs)
        peaks = detect_r_peaks(raw, filtered, fs)
        if len(peaks) < 3:
            raise ValueError("Fewer than three R peaks were detected; review the ECG recording.")
        flags: list[str] = []
        expected_step = 1.0 / fs
        if np.any(np.diff(time) > 1.5 * expected_step):
            flags.append("Sample-time gaps are present.")
        low_clip = int(np.sum(raw <= 1))
        high_clip = int(np.sum(raw >= 4094))
        if low_clip or high_clip:
            flags.append("Possible 12-bit ADC clipping is present.")
        rr = np.diff(time[peaks])
        if np.any((rr < 0.30) | (rr > 2.0)):
            flags.append("At least one detected R–R interval needs manual review.")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        return cls(
            source_path=path,
            source_sha256=digest,
            time_s=time,
            raw_signal=raw,
            filtered_signal=filtered,
            fs_hz=fs,
            channel_name=channel_name,
            time_column_name=time_name,
            r_peaks=np.asarray(peaks, dtype=int),
            quality_flags=flags,
        )

    @property
    def duration_s(self) -> float:
        return float(self.time_s[-1] - self.time_s[0])

    @property
    def beat_count(self) -> int:
        return max(0, len(self.beat_boundary_samples) - 1)

    @property
    def beat_boundary_samples(self) -> np.ndarray:
        """Return measured R-trigger boundaries for the shared playback clock."""

        return np.asarray(self.r_peaks, dtype=int)

    @property
    def cycle_reference_name(self) -> str:
        return "reviewed R-peak"

    @property
    def rr_s(self) -> np.ndarray:
        return np.diff(self.time_s[self.beat_boundary_samples])

    @property
    def mean_heart_rate_bpm(self) -> float:
        return float(60.0 / np.mean(self.rr_s))

    def beat_duration_ms(self, beat_index: int) -> float:
        beat = int(np.clip(beat_index, 0, max(0, self.beat_count - 1)))
        return float(self.rr_s[beat] * 1000.0)

    def beat_start_time_s(self, beat_index: int) -> float:
        beat = int(np.clip(beat_index, 0, max(0, self.beat_count - 1)))
        return float(self.time_s[self.beat_boundary_samples[beat]])

    def landmark(self, kind: str, beat_index: int) -> ECGLandmark | None:
        matches = [
            item
            for item in self.landmarks
            if item.kind == str(kind) and item.beat_index == int(beat_index)
        ]
        if not matches:
            return None
        source_priority = {
            "manual": 4,
            "template_reviewed": 3,
            "template_automatic": 2,
            "automatic": 1,
        }
        return max(
            matches,
            key=lambda item: (source_priority.get(item.source, 0), item.confidence),
        )

    def _rebuild_median_template(self, preserve_reviewed: bool = True) -> None:
        reviewed_offsets: dict[str, float] = {}
        if preserve_reviewed and self.median_template is not None:
            reviewed_offsets = {
                kind: float(value)
                for kind, value in self.median_template.landmark_offsets_s.items()
                if self.median_template.landmark_sources.get(kind) == "template_reviewed"
            }
        template = build_median_template(self.filtered_signal, self.r_peaks, self.fs_hz)
        for kind, value in reviewed_offsets.items():
            if kind in ELECTRICAL_KINDS:
                template.landmark_offsets_s[kind] = float(value)
                template.landmark_sources[kind] = "template_reviewed"
        self.median_template = template

    def _project_template(self, preserved: Iterable[ECGLandmark] = ()) -> None:
        if self.median_template is None:
            self._rebuild_median_template(preserve_reviewed=False)
        projected = project_template_landmarks(
            self.median_template,
            self.r_peaks,
            self.fs_hz,
            len(self.filtered_signal),
        )
        preserved_items = [
            item
            for item in preserved
            if item.kind not in LEGACY_T_KINDS
            and (item.group == "mechanical" or item.kind == "r_peak")
        ]
        preserved_keys = {(item.kind, item.beat_index) for item in preserved_items}
        self.landmarks = [
            item for item in projected if (item.kind, item.beat_index) not in preserved_keys
        ] + preserved_items
        self.landmarks.sort(key=lambda value: (value.sample_index, value.kind))

    def set_template_landmark_offset(self, kind: str, offset_s: float) -> None:
        """Review one P/QRS point on the median template and reproject it."""

        if kind not in TEMPLATE_EDITABLE_KINDS:
            raise ValueError("Only P onset, P peak, QRS onset and QRS end are editable on the template.")
        if self.median_template is None:
            self._rebuild_median_template(preserve_reviewed=False)
        offset = float(offset_s)
        lower, upper = float(self.median_template.offsets_s[0]), float(self.median_template.offsets_s[-1])
        if not lower <= offset <= upper:
            raise ValueError("The marker lies outside the median-template window.")
        proposed = dict(self.median_template.landmark_offsets_s)
        proposed[kind] = offset
        ordering = [
            proposed[kind]
            for kind in ("p_onset", "p_peak", "qrs_onset")
            if kind in proposed
        ] + [0.0] + (
            [proposed["qrs_offset"]] if "qrs_offset" in proposed else []
        )
        if not np.all(np.diff(ordering) > 0):
            raise ValueError("Markers must remain ordered P onset → P peak → QRS onset → R → QRS end.")
        self.median_template.landmark_offsets_s[kind] = offset
        self.median_template.landmark_sources[kind] = "template_reviewed"
        preserved = [item for item in self.landmarks if item.source == "manual"]
        self._project_template(preserved)

    def reset_template_landmark(self, kind: str) -> None:
        if kind not in TEMPLATE_EDITABLE_KINDS:
            raise ValueError("This marker is not editable on the median template.")
        fresh = build_median_template(self.filtered_signal, self.r_peaks, self.fs_hz)
        if kind not in fresh.landmark_offsets_s:
            raise ValueError(f"No automatic {LANDMARK_SPECS[kind][0]} suggestion is available.")
        if self.median_template is None:
            self.median_template = fresh
        else:
            self.median_template.landmark_offsets_s[kind] = fresh.landmark_offsets_s[kind]
            self.median_template.landmark_sources[kind] = "template_automatic"
        preserved = [item for item in self.landmarks if item.source == "manual"]
        self._project_template(preserved)

    def landmark_time_s(self, kind: str, beat_index: int) -> float | None:
        item = self.landmark(kind, beat_index)
        if item is None:
            return None
        return float(self.time_s[int(item.sample_index)])

    def beat_index_at_time(self, time_s: float) -> int:
        boundaries = self.time_s[self.beat_boundary_samples]
        beat = int(np.searchsorted(boundaries, float(time_s), side="right") - 1)
        return int(np.clip(beat, 0, max(0, self.beat_count - 1)))

    def set_landmark_at_time(
        self,
        kind: str,
        time_s: float,
        beat_index: int | None = None,
        note: str = "",
    ) -> ECGLandmark:
        if kind not in LANDMARK_SPECS:
            raise ValueError(f"Unsupported annotation type: {kind}")
        if kind in LEGACY_T_KINDS:
            raise ValueError("T-wave annotations are not used by this synchronization model.")
        sample = int(np.argmin(np.abs(self.time_s - float(time_s))))
        if kind == "r_peak":
            if not len(self.r_peaks):
                raise ValueError("No existing R marker is available to move.")
            nearest = int(np.argmin(np.abs(self.time_s[self.r_peaks] - float(time_s))))
            updated = self.r_peaks.copy()
            updated[nearest] = sample
            updated = np.sort(updated)
            if np.any(np.diff(updated) < int(round(0.25 * self.fs_hz))):
                raise ValueError("The moved R marker would lie within 250 ms of another beat.")
            self.r_peaks = updated
            self.redetect_landmarks(preserve_manual=True)
            moved_beat = int(np.argmin(np.abs(self.r_peaks - sample)))
            self.landmarks = [
                existing
                for existing in self.landmarks
                if not (existing.kind == "r_peak" and existing.beat_index == moved_beat)
            ]
            item = ECGLandmark(
                kind="r_peak",
                sample_index=sample,
                beat_index=moved_beat,
                source="manual",
                confidence=1.0,
                note=str(note),
            )
            self.landmarks.append(item)
            self.landmarks.sort(key=lambda value: (value.sample_index, value.kind))
            return item
        if beat_index is None:
            beat_index = self.beat_index_at_time(time_s)
            if kind in {"p_onset", "p_peak", "qrs_onset", "r_peak", "qrs_offset"}:
                r_times = self.time_s[self.r_peaks]
                beat_index = int(np.argmin(np.abs(r_times - float(time_s))))
        item = ECGLandmark(
            kind=kind,
            sample_index=sample,
            beat_index=int(beat_index),
            source="manual",
            confidence=1.0,
            note=str(note),
        )
        self.landmarks = [
            existing
            for existing in self.landmarks
            if not (existing.kind == kind and existing.beat_index == int(beat_index))
        ]
        self.landmarks.append(item)
        self.landmarks.sort(key=lambda value: (value.sample_index, value.kind))
        return item

    def remove_landmark_near_time(
        self, time_s: float, kind: str | None = None, tolerance_s: float = 0.12
    ) -> ECGLandmark:
        candidates = [
            item for item in self.landmarks if kind is None or item.kind == str(kind)
        ]
        if not candidates:
            raise ValueError("No matching annotation is available.")
        nearest = min(
            candidates,
            key=lambda item: abs(float(self.time_s[item.sample_index]) - float(time_s)),
        )
        if abs(float(self.time_s[nearest.sample_index]) - float(time_s)) > tolerance_s:
            raise ValueError("No matching annotation lies within 120 ms of the cursor.")
        if nearest.kind == "r_peak":
            raise ValueError("Use the dedicated R-marker control to remove a beat boundary.")
        self.landmarks.remove(nearest)
        return nearest

    def redetect_landmarks(self, preserve_manual: bool = True) -> None:
        manual = [
            item
            for item in self.landmarks
            if preserve_manual and item.source == "manual" and item.kind not in LEGACY_T_KINDS
        ]
        self._rebuild_median_template(preserve_reviewed=preserve_manual)
        automatic = suggest_landmarks(
            self.filtered_signal,
            self.r_peaks,
            self.fs_hz,
            self.median_template,
        )
        for item in manual:
            if item.kind in ELECTRICAL_KINDS:
                item.beat_index = int(np.argmin(np.abs(self.r_peaks - item.sample_index)))
            elif len(self.r_peaks) >= 2:
                item.beat_index = int(
                    np.clip(
                        np.searchsorted(self.r_peaks, item.sample_index, side="right") - 1,
                        0,
                        max(0, self.beat_count - 1),
                    )
                )
        manual_keys = {(item.kind, item.beat_index) for item in manual}
        self.landmarks = [
            item for item in automatic if (item.kind, item.beat_index) not in manual_keys
        ] + manual
        self.landmarks.sort(key=lambda value: (value.sample_index, value.kind))

    def save_annotations(self, path: Path) -> None:
        save_annotation_sidecar(
            Path(path),
            annotation_payload(
                self.source_sha256,
                self.fs_hz,
                self.channel_name,
                self.landmarks,
                self.median_template,
            ),
        )

    def load_annotations(self, path: Path) -> None:
        payload, landmarks = load_annotation_sidecar(Path(path))
        if str(payload.get("source_sha256", "")) != self.source_sha256:
            raise ValueError("This annotation sidecar belongs to a different ECG file.")
        if not landmarks:
            raise ValueError("The sidecar contains no supported annotations.")
        self.landmarks = [
            item
            for item in landmarks
            if 0 <= item.sample_index < len(self.time_s) and item.kind not in LEGACY_T_KINDS
        ]
        r_markers = sorted(
            item.sample_index for item in self.landmarks if item.kind == "r_peak"
        )
        if len(r_markers) >= 3:
            self.r_peaks = np.asarray(r_markers, dtype=int)
        self._rebuild_median_template(preserve_reviewed=False)
        template_payload = payload.get("median_template", {})
        offsets = template_payload.get("landmark_offsets_s", {})
        sources = template_payload.get("landmark_sources", {})
        if isinstance(offsets, dict):
            for kind, value in offsets.items():
                if kind not in ELECTRICAL_KINDS:
                    continue
                try:
                    self.median_template.landmark_offsets_s[kind] = float(value)
                    self.median_template.landmark_sources[kind] = str(
                        sources.get(kind, "template_reviewed")
                    )
                except (TypeError, ValueError):
                    continue
        preserved = [item for item in self.landmarks if item.source == "manual"]
        self._project_template(preserved)

    def replace_peaks(self, peaks: Iterable[int]) -> None:
        cleaned = sorted({int(value) for value in peaks if 0 <= int(value) < len(self.time_s)})
        if len(cleaned) < 3:
            raise ValueError("At least three R peaks are required for ECG-gated playback.")
        self.r_peaks = np.asarray(cleaned, dtype=int)
        self.redetect_landmarks(preserve_manual=True)

    def add_peak_at_time(self, time_s: float) -> int:
        centre = int(np.argmin(np.abs(self.time_s - float(time_s))))
        radius = max(1, int(round(0.08 * self.fs_hz)))
        start = max(0, centre - radius)
        stop = min(len(self.filtered_signal), centre + radius + 1)
        local = self.filtered_signal[start:stop]
        peak = start + int(np.argmax(np.abs(local - np.median(local))))
        minimum_distance = int(round(0.25 * self.fs_hz))
        if len(self.r_peaks) and int(np.min(np.abs(self.r_peaks - peak))) < minimum_distance:
            raise ValueError("A detected R peak already lies within 250 ms of that position.")
        self.replace_peaks([*self.r_peaks.tolist(), peak])
        return peak

    def remove_peak_near_time(self, time_s: float, tolerance_s: float = 0.20) -> int:
        times = self.time_s[self.r_peaks]
        nearest = int(np.argmin(np.abs(times - float(time_s))))
        if abs(float(times[nearest]) - float(time_s)) > float(tolerance_s):
            raise ValueError("No R marker lies within 200 ms of the cursor.")
        removed = int(self.r_peaks[nearest])
        self.replace_peaks(np.delete(self.r_peaks, nearest))
        return removed
